### PR TITLE
Use Englezos's repos

### PR DESCRIPTION
**Pull request by AirOne70**

### CODE REVIEW

**Comment by erhan-** [comment]
Thank you very much for your contribution to this project. Have you been able to test this already ?

**Comment by AirOne70** [comment]
You're welcome. I built this rom using this manifest yes, but not using your script.

**Comment by erhan-** [comment]
Thanks again! I will merge this into here now.

**Comment by AirOne70** [comment]
But be aware that Englezos is modifying / reworking the content of these repositories very frequently, because he is not satisfied. So the current content may not be working well, it's still "work in progress".

**Comment by erhan-** [comment]
I think it would pull the latest changes also from his repositories on each build, right? I thought you were Englezos at first but he has an own account.

**Comment by erhan-** [comment]
@AirOne70 If you build your rom successfully, then something with the process here is wrong. With the current image and configuration, this will be the output:

```
repo sync has finished successfully.
Device raphael not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_xiaomi_raphael
Default revision: lineage-18.1
Checking branch info
Checking if device/xiaomi/raphael is fetched from android_device_xiaomi_raphael
Adding dependency: LineageOS/android_device_xiaomi_raphael -> device/xiaomi/raphael
Using default branch for android_device_xiaomi_raphael
Syncing repository to retrieve project.
Repository synced!
Looking for dependencies in device/xiaomi/raphael
Adding dependencies to manifest
Checking if device/xiaomi/sm8150-common is fetched from android_device_xiaomi_sm8150-common
Adding dependency: LineageOS/android_device_xiaomi_sm8150-common -> device/xiaomi/sm8150-common
Using default branch for android_device_xiaomi_sm8150-common
Syncing dependencies
Looking for dependencies in device/xiaomi/sm8150-common
Adding dependencies to manifest
Checking if hardware/xiaomi is fetched from android_hardware_xiaomi
Adding dependency: LineageOS/android_hardware_xiaomi -> hardware/xiaomi
Using default branch for android_hardware_xiaomi
Checking if kernel/xiaomi/sm8150 is fetched from android_kernel_xiaomi_sm8150
Adding dependency: LineageOS/android_kernel_xiaomi_sm8150 -> kernel/xiaomi/sm8150
Using default branch for android_kernel_xiaomi_sm8150
Syncing dependencies
Looking for dependencies in hardware/xiaomi
hardware/xiaomi has no additional dependencies.
Looking for dependencies in kernel/xiaomi/sm8150
kernel/xiaomi/sm8150 has no additional dependencies.
Done
14:19:41 Build sandboxing disabled due to nsjail error.
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
[1mbuild/make/target/product/updatable_apex.mk:24: [31merror: [0m[1m_nic.PRODUCTS.[[device/xiaomi/raphael/lineage_raphael.mk]]: "vendor/xiaomi/sm8150-common/sm8150-common-vendor.mk" does not exist.[0m
14:19:42 dumpvars failed with: exit status 1
14:21:25 Build sandboxing disabled due to nsjail error.
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
[1mbuild/make/target/product/updatable_apex.mk:24: [31merror: [0m[1m_nic.PRODUCTS.[[device/xiaomi/raphael/lineage_raphael.mk]]: "vendor/xiaomi/sm8150-common/sm8150-common-vendor.mk" does not exist.[0m
14:21:26 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_raphael'
** Do you have the right repo manifest?

No such item in brunch menu. Try 'breakfast'
>> [Sat Dec  4 14:21:26 UTC 2021] Failed build for raphael
>> [Sat Dec  4 14:21:26 UTC 2021] Finishing build for raphael
>> [Sat Dec  4 14:21:26 UTC 2021] Cleaning source dir for device raphael
14:23:10 Entire build directory removed.

#### build completed successfully (01:44 (mm:ss)) ####
```

**Comment by AirOne70** [comment]
It was working on the day I created this request, but we are now few months later and some things changed since then. From your logs, it seems like your custom manifest file is not used at all.
I'm not building LineageOS 18.1 anymore since I switched to Android 12 (ArrowOS 12), but I will try to update your manifest entries.

**Comment by erhan-** [comment]
I confirm that this is working now and I am writing from the built system!

Thank you very much. This will give some more freedom to people!

**Comment by AirOne70** [comment]
Happy to hear that! Enjoy your freshly built system. ;)

**Comment by erhan-** [comment]
I use it daily and heavy and everything is stable.

**Pull request merged**
